Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using test.BLL;
using test.Models;

namespace project.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentBLL departmentBLL = new DepartmentBLL();
        public IActionResult Index()
        {
            var departments = departmentBLL.getAll();
            return View(departments);
        }
        public IActionResult Details(int? id)
        {
            if (id is null)
                return BadRequest("U didn't provide the id");

            var department = departmentBLL.getDepartment(id.Value);
            if (department is null)
                return NotFound("No department with such id");
            return View(department);
        }
        [HttpPost]
        public IActionResult Create(Department d)
        {
            if (d is null)
                return BadRequest();
            departmentBLL.Add(d);
            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id is null)
                return BadRequest();
            departmentBLL.Delete(id.Value);

            return RedirectToAction("index");
        }
        [HttpPost]
        public IActionResult Update(Department dept)
        {
            departmentBLL.update(dept);
            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id is null)
                return BadRequest("U didn't provide the id");

            var department = departmentBLL.getDepartment(id.Value);
            if (department is null)
                return NotFound("No department with such id");

            return View(department);
        }
        public IActionResult Search(string item)
        {
            if (item is null)
                return BadRequest();
            IEnumerable<Department> departments= departmentBLL.SearchByName(item);
            if (departments.IsNullOrEmpty())
                return NotFound("Nothing Matched");
            return View(departments);

        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using project.ActionFilters;
using test.BLL;
using test.Context;
using test.Models;

namespace test.Controllers
{
    public class StudentController:Controller
    {
  
        StudentBLL studentBLL=new StudentBLL();
        DepartmentBLL departmentBLL=new DepartmentBLL();

        [CreatesStudentException]// calling the action filter I made
        public IActionResult Index()
        {
            /*
             let's simulate that we have an error in this action, 
             first of all, we code in protective programming way
             trying not to collide with errors, after that if we 
             suspect that a line of code will generate an error 
             we do the try catch approach,
             we can protect our code furthermore in the scenario where
             we don't suspect that this action will generate an error
             but if happened we will display to the user an error view
             explaining what happened or anything (this is what we gonna do here 
             and we call this *ACTION FILTERS*)
            */

            /*  int x = int.Parse("sf"); => error simulation */
            
            var students = studentBLL.getAll();
            return View(students);
        }
        public IActionResult Search(string item)
        {
            if (item is null)
                return BadRequest();
            IEnumerable<Student> students = studentBLL.SearchByName(item);
            if (students.IsNullOrEmpty())
                return NotFound("Nothing Matched");
   
            return View(students);
            
        }
        public IActionResult Details(int? id)
        { 
            if (id is null)
                return BadRequest();
            Student student = studentBLL.getStudent(id.Value);
            if(student is null)
                return NotFound();
            return View(student);
        }
        // model binder priorities from higher to lower :
        // model binder will search first in Request.Form => Request.RouteValues => Request.Query
        // this is the default behaviour but what if I wanted the model binder to just search in
        // queryString or RouteValues or PostedData(Form)
        // you have to add some attribute before the paramter, see parameter of Create function below
        // [FromForm] : Search in posted Data (Request.Form)
        // [FromQuery] : Search in query string (Request.Query)
        // [FromRoute] : Search in routed values (Request.RouteValues)

        [HttpPost] //cuz i have 2 functions with the same name, THIS IS CALLES ACTION SELECTOR
        public IActionResult Create(/*[FromRoute]*/ Student st) { 

            if(ModelState.IsValid)
            {
                studentBLL.Add(st);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.departments = new SelectList(departmentBLL.getAll(), "Id", "Name");
                return View(st);
            }
        }

        [HttpGet]
        public IActionResult Create() {
          ViewBag.departments=new SelectList(departmentBLL.getAll(),"Id","Name");
            return View("Create");
        }
        public IActionResult Delete(int? id) {
            if(id is null) 
                return BadRequest();
            var st=studentBLL.getStudent(id.Value);
            if(st is null)
                return NotFound("There is no such student with the id u sent");
            studentBLL.Delete(st);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Update(Student st) {
            studentBLL.Update(st);
            
            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id is null)
                return BadRequest();
            Student st = studentBLL.getStudent(id.Value);
            if (st is null)
                return NotFound("No student with such id");
            ViewBag.depts = new SelectList(departmentBLL.getAll(), "Id", "Name");
            return View(st);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/test.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a style="color:white" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>